// generated by cdk8s
import { Chart, ApiObject } from 'cdk8s';
import * as group from '../imports/apiextensions.crossplane.io';

export function eksAwsPlatformrefCrossplaneIo(chart: Chart, name: string = 'eks.aws.platform.acme.io/compositeresourcedefinition/apiextensions.crossplane.io') : ApiObject {
  return new group.CompositeResourceDefinition(chart, name,
    {
      metadata: {
        name: 'eks.aws.platform.acme.io',
      },
      spec: {
        connectionSecretKeys: [
          'kubeconfig',
        ],
        group: 'aws.platform.acme.io',
        names: {
          kind: 'EKS',
          plural: 'eks',
        },
        versions: [
          {
            name: 'v1alpha1',
            served: true,
            referenceable: true,
            schema: {
              openAPIV3Schema: {
                type: 'object',
                properties: {
                  spec: {
                    type: 'object',
                    properties: {
                      id: {
                        type: 'string',
                        description: 'ID of this Cluster that other objects will use to refer to it.',
                      },
                      parameters: {
                        type: 'object',
                        description: 'EKS configuration parameters.',
                        properties: {
                          nodes: {
                            type: 'object',
                            description: 'EKS node configuration parameters.',
                            properties: {
                              count: {
                                type: 'integer',
                                description: 'Desired node count, from 1 to 100.',
                              },
                              size: {
                                type: 'string',
                                description: 'Size of node.',
                                enum: [
                                  'small',
                                  'medium',
                                  'large',
                                ],
                              },
                            },
                            required: [
                              'count',
                              'size',
                            ],
                          },
                          networkRef: {
                            type: 'object',
                            description: 'A reference to the Network object that this postgres should be connected to.',
                            properties: {
                              id: {
                                type: 'string',
                                description: 'ID of the Network object this ref points to.',
                              },
                            },
                            required: [
                              'id',
                            ],
                          },
                        },
                        required: [
                          'nodes',
                          'networkRef',
                        ],
                      },
                    },
                    required: [
                      'parameters',
                    ],
                  },
                },
              },
            },
          },
        ],
      },
    }
  );
}

export function servicesAwsPlatformrefCrossplaneIo(chart: Chart, name: string = 'services.aws.platform.acme.io/compositeresourcedefinition/apiextensions.crossplane.io') : ApiObject {
  return new group.CompositeResourceDefinition(chart, name,
    {
      metadata: {
        name: 'services.aws.platform.acme.io',
      },
      spec: {
        group: 'aws.platform.acme.io',
        names: {
          kind: 'Services',
          plural: 'services',
        },
        versions: [
          {
            name: 'v1alpha1',
            served: true,
            referenceable: true,
            schema: {
              openAPIV3Schema: {
                type: 'object',
                properties: {
                  spec: {
                    type: 'object',
                    properties: {
                      operators: {
                        type: 'object',
                        description: 'Configuration for operators.',
                        properties: {
                          prometheus: {
                            type: 'object',
                            description: 'Configuration for the Prometheus operator.',
                            properties: {
                              version: {
                                type: 'string',
                                description: 'Prometheus operator version to run.',
                              },
                            },
                          },
                        },
                      },
                      providerConfigRef: {
                        type: 'object',
                        description: 'A reference to the ProviderConfig of the cluster that services should be deployed to.',
                        properties: {
                          name: {
                            type: 'string',
                            description: 'Name of the Kubernetes provider configuration. This will typically be the name of the cluster with a five character suffix appended.',
                          },
                        },
                        required: [
                          'name',
                        ],
                      },
                    },
                    required: [
                      'providerConfigRef',
                    ],
                  },
                },
              },
            },
          },
        ],
      },
    }
  );
}

export function compositenetworksAwsPlatformrefCrossplaneIo(chart: Chart, name: string = 'compositenetworks.aws.platform.acme.io/compositeresourcedefinition/apiextensions.crossplane.io') : ApiObject {
  return new group.CompositeResourceDefinition(chart, name,
    {
      metadata: {
        name: 'compositenetworks.aws.platform.acme.io',
        annotations: {
          'upbound.io/ui-schema': '---\nconfigSections:\n- title: Network Info\n  description: Information about this network fabric\n  items:\n  - name: id\n    controlType: singleInput\n    type: string\n    path: ".spec.id"\n    title: Network ID\n    description: Network ID that other objects will use to refer (and connect) to this network fabric\n    default: acme-platform-aws-network\n    validation:\n    - required: true\n      customError: Network ID is required.\n- title: Cluster Info\n  description: The cluster used with this network fabric\n  items:\n  - name: clusterRef\n    controlType: singleInput\n    type: string\n    path: ".spec.clusterRef.id"\n    title: Cluster Ref\n    description: ID of the Cluster object that will use this network fabric\n    default: acme-platform-aws-cluster\n    validation:\n    - required: true\n      customError: Cluster ref is required.',
        },
      },
      spec: {
        claimNames: {
          kind: 'Network',
          plural: 'networks',
        },
        group: 'aws.platform.acme.io',
        names: {
          kind: 'CompositeNetwork',
          plural: 'compositenetworks',
        },
        versions: [
          {
            name: 'v1alpha1',
            served: true,
            referenceable: true,
            schema: {
              openAPIV3Schema: {
                type: 'object',
                properties: {
                  spec: {
                    type: 'object',
                    properties: {
                      id: {
                        type: 'string',
                        description: 'ID of this Network that other objects will use to refer to it.',
                      },
                      clusterRef: {
                        type: 'object',
                        description: 'A reference to the Cluster object that this network will be used for.',
                        properties: {
                          id: {
                            type: 'string',
                            description: 'ID of the Cluster object this ref points to.',
                          },
                        },
                        required: [
                          'id',
                        ],
                      },
                    },
                    required: [
                      'id',
                      'clusterRef',
                    ],
                  },
                },
              },
            },
          },
        ],
      },
    }
  );
}

