// generated by cdk8s
import { ApiObject } from 'cdk8s';
import { Construct } from 'constructs';

/**
 * An IAMGroupPolicyAttachment is a managed resource that represents an AWS IAM Group policy attachment.
 *
 * @schema IAMGroupPolicyAttachment
 */
export class IamGroupPolicyAttachment extends ApiObject {
  /**
   * Defines a "IAMGroupPolicyAttachment" API object
   * @param scope the scope in which to define this object
   * @param name a scope-local name for the object
   * @param options configuration options
   */
  public constructor(scope: Construct, name: string, options: IamGroupPolicyAttachmentOptions) {
    super(scope, name, {
      ...options,
      kind: 'IAMGroupPolicyAttachment',
      apiVersion: 'identity.aws.crossplane.io/v1alpha1',
    });
  }
}

/**
 * An IAMGroupPolicyAttachment is a managed resource that represents an AWS IAM Group policy attachment.
 *
 * @schema IAMGroupPolicyAttachment
 */
export interface IamGroupPolicyAttachmentOptions {
  /**
   * @schema IAMGroupPolicyAttachment#metadata
   */
  readonly metadata?: any;

  /**
   * An IAMGroupPolicyAttachmentSpec defines the desired state of an IAMGroupPolicyAttachment.
   *
   * @schema IAMGroupPolicyAttachment#spec
   */
  readonly spec: IamGroupPolicyAttachmentSpec;

}

/**
 * An IAMGroupPolicyAttachmentSpec defines the desired state of an IAMGroupPolicyAttachment.
 *
 * @schema IamGroupPolicyAttachmentSpec
 */
export interface IamGroupPolicyAttachmentSpec {
  /**
   * DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource. The "Delete" policy is the default when no policy is specified.
   *
   * @schema IamGroupPolicyAttachmentSpec#deletionPolicy
   */
  readonly deletionPolicy?: IamGroupPolicyAttachmentSpecDeletionPolicy;

  /**
   * IAMGroupPolicyAttachmentParameters define the desired state of an AWS IAMGroupPolicyAttachment.
   *
   * @schema IamGroupPolicyAttachmentSpec#forProvider
   */
  readonly forProvider: IamGroupPolicyAttachmentSpecForProvider;

  /**
   * ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured.
   *
   * @schema IamGroupPolicyAttachmentSpec#providerConfigRef
   */
  readonly providerConfigRef?: IamGroupPolicyAttachmentSpecProviderConfigRef;

  /**
   * ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`
   *
   * @schema IamGroupPolicyAttachmentSpec#providerRef
   */
  readonly providerRef?: IamGroupPolicyAttachmentSpecProviderRef;

  /**
   * WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource.
   *
   * @schema IamGroupPolicyAttachmentSpec#writeConnectionSecretToRef
   */
  readonly writeConnectionSecretToRef?: IamGroupPolicyAttachmentSpecWriteConnectionSecretToRef;

}

/**
 * DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource. The "Delete" policy is the default when no policy is specified.
 *
 * @schema IamGroupPolicyAttachmentSpecDeletionPolicy
 */
export enum IamGroupPolicyAttachmentSpecDeletionPolicy {
  /** Orphan */
  ORPHAN = 'Orphan',
  /** Delete */
  DELETE = 'Delete',
}

/**
 * IAMGroupPolicyAttachmentParameters define the desired state of an AWS IAMGroupPolicyAttachment.
 *
 * @schema IamGroupPolicyAttachmentSpecForProvider
 */
export interface IamGroupPolicyAttachmentSpecForProvider {
  /**
   * GroupName presents the name of the IAMGroup.
   *
   * @schema IamGroupPolicyAttachmentSpecForProvider#groupName
   */
  readonly groupName?: string;

  /**
   * GroupNameRef references to an IAMGroup to retrieve its groupName
   *
   * @schema IamGroupPolicyAttachmentSpecForProvider#groupNameRef
   */
  readonly groupNameRef?: IamGroupPolicyAttachmentSpecForProviderGroupNameRef;

  /**
   * GroupNameSelector selects a reference to an IAMGroup to retrieve its groupName
   *
   * @schema IamGroupPolicyAttachmentSpecForProvider#groupNameSelector
   */
  readonly groupNameSelector?: IamGroupPolicyAttachmentSpecForProviderGroupNameSelector;

  /**
   * PolicyARN is the Amazon Resource Name (ARN) of the IAM policy you want to attach.
   *
   * @schema IamGroupPolicyAttachmentSpecForProvider#policyArn
   */
  readonly policyArn?: string;

  /**
   * PolicyARNRef references an IAMPolicy to retrieve its Policy ARN.
   *
   * @schema IamGroupPolicyAttachmentSpecForProvider#policyArnRef
   */
  readonly policyArnRef?: IamGroupPolicyAttachmentSpecForProviderPolicyArnRef;

  /**
   * PolicyARNSelector selects a reference to an IAMPolicy to retrieve its Policy ARN
   *
   * @schema IamGroupPolicyAttachmentSpecForProvider#policyArnSelector
   */
  readonly policyArnSelector?: IamGroupPolicyAttachmentSpecForProviderPolicyArnSelector;

}

/**
 * ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured.
 *
 * @schema IamGroupPolicyAttachmentSpecProviderConfigRef
 */
export interface IamGroupPolicyAttachmentSpecProviderConfigRef {
  /**
   * Name of the referenced object.
   *
   * @schema IamGroupPolicyAttachmentSpecProviderConfigRef#name
   */
  readonly name: string;

}

/**
 * ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`
 *
 * @schema IamGroupPolicyAttachmentSpecProviderRef
 */
export interface IamGroupPolicyAttachmentSpecProviderRef {
  /**
   * Name of the referenced object.
   *
   * @schema IamGroupPolicyAttachmentSpecProviderRef#name
   */
  readonly name: string;

}

/**
 * WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource.
 *
 * @schema IamGroupPolicyAttachmentSpecWriteConnectionSecretToRef
 */
export interface IamGroupPolicyAttachmentSpecWriteConnectionSecretToRef {
  /**
   * Name of the secret.
   *
   * @schema IamGroupPolicyAttachmentSpecWriteConnectionSecretToRef#name
   */
  readonly name: string;

  /**
   * Namespace of the secret.
   *
   * @schema IamGroupPolicyAttachmentSpecWriteConnectionSecretToRef#namespace
   */
  readonly namespace: string;

}

/**
 * GroupNameRef references to an IAMGroup to retrieve its groupName
 *
 * @schema IamGroupPolicyAttachmentSpecForProviderGroupNameRef
 */
export interface IamGroupPolicyAttachmentSpecForProviderGroupNameRef {
  /**
   * Name of the referenced object.
   *
   * @schema IamGroupPolicyAttachmentSpecForProviderGroupNameRef#name
   */
  readonly name: string;

}

/**
 * GroupNameSelector selects a reference to an IAMGroup to retrieve its groupName
 *
 * @schema IamGroupPolicyAttachmentSpecForProviderGroupNameSelector
 */
export interface IamGroupPolicyAttachmentSpecForProviderGroupNameSelector {
  /**
   * MatchControllerRef ensures an object with the same controller reference as the selecting object is selected.
   *
   * @schema IamGroupPolicyAttachmentSpecForProviderGroupNameSelector#matchControllerRef
   */
  readonly matchControllerRef?: boolean;

  /**
   * MatchLabels ensures an object with matching labels is selected.
   *
   * @schema IamGroupPolicyAttachmentSpecForProviderGroupNameSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

}

/**
 * PolicyARNRef references an IAMPolicy to retrieve its Policy ARN.
 *
 * @schema IamGroupPolicyAttachmentSpecForProviderPolicyArnRef
 */
export interface IamGroupPolicyAttachmentSpecForProviderPolicyArnRef {
  /**
   * Name of the referenced object.
   *
   * @schema IamGroupPolicyAttachmentSpecForProviderPolicyArnRef#name
   */
  readonly name: string;

}

/**
 * PolicyARNSelector selects a reference to an IAMPolicy to retrieve its Policy ARN
 *
 * @schema IamGroupPolicyAttachmentSpecForProviderPolicyArnSelector
 */
export interface IamGroupPolicyAttachmentSpecForProviderPolicyArnSelector {
  /**
   * MatchControllerRef ensures an object with the same controller reference as the selecting object is selected.
   *
   * @schema IamGroupPolicyAttachmentSpecForProviderPolicyArnSelector#matchControllerRef
   */
  readonly matchControllerRef?: boolean;

  /**
   * MatchLabels ensures an object with matching labels is selected.
   *
   * @schema IamGroupPolicyAttachmentSpecForProviderPolicyArnSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

}

