// generated by cdk8s
import { ApiObject } from 'cdk8s';
import { Construct } from 'constructs';

/**
 * A CacheCluster is a managed resource that represents an AWS ElastiCache Cache Cluster.
 *
 * @schema CacheCluster
 */
export class CacheCluster extends ApiObject {
  /**
   * Defines a "CacheCluster" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialiation props
   */
  public constructor(scope: Construct, id: string, props: CacheClusterProps) {
    super(scope, id, {
      ...props,
      kind: 'CacheCluster',
      apiVersion: 'cache.aws.crossplane.io/v1alpha1',
    });
  }
}

/**
 * A CacheCluster is a managed resource that represents an AWS ElastiCache Cache Cluster.
 *
 * @schema CacheCluster
 */
export interface CacheClusterProps {
  /**
   * @schema CacheCluster#metadata
   */
  readonly metadata?: any;

  /**
   * A CacheClusterSpec defines the desired state of a CacheCluster.
   *
   * @schema CacheCluster#spec
   */
  readonly spec: CacheClusterSpec;

}

/**
 * A CacheClusterSpec defines the desired state of a CacheCluster.
 *
 * @schema CacheClusterSpec
 */
export interface CacheClusterSpec {
  /**
   * DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource. The "Delete" policy is the default when no policy is specified.
   *
   * @schema CacheClusterSpec#deletionPolicy
   */
  readonly deletionPolicy?: CacheClusterSpecDeletionPolicy;

  /**
   * CacheClusterParameters define the desired state of an AWS ElastiCache Cache Cluster. Most fields map directly to an AWS ReplicationGroup: https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateReplicationGroup.html#API_CreateReplicationGroup_RequestParameters
   *
   * @schema CacheClusterSpec#forProvider
   */
  readonly forProvider: CacheClusterSpecForProvider;

  /**
   * ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured.
   *
   * @schema CacheClusterSpec#providerConfigRef
   */
  readonly providerConfigRef?: CacheClusterSpecProviderConfigRef;

  /**
   * ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`
   *
   * @schema CacheClusterSpec#providerRef
   */
  readonly providerRef?: CacheClusterSpecProviderRef;

  /**
   * WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource.
   *
   * @schema CacheClusterSpec#writeConnectionSecretToRef
   */
  readonly writeConnectionSecretToRef?: CacheClusterSpecWriteConnectionSecretToRef;

}

/**
 * DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource. The "Delete" policy is the default when no policy is specified.
 *
 * @schema CacheClusterSpecDeletionPolicy
 */
export enum CacheClusterSpecDeletionPolicy {
  /** Orphan */
  ORPHAN = "Orphan",
  /** Delete */
  DELETE = "Delete",
}

/**
 * CacheClusterParameters define the desired state of an AWS ElastiCache Cache Cluster. Most fields map directly to an AWS ReplicationGroup: https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateReplicationGroup.html#API_CreateReplicationGroup_RequestParameters
 *
 * @schema CacheClusterSpecForProvider
 */
export interface CacheClusterSpecForProvider {
  /**
   * If true, this parameter causes the modifications in this request and any pending modifications to be applied, asynchronously and as soon as possible, regardless of the PreferredMaintenanceWindow setting for the cluster. If false, changes to the cluster are applied on the next maintenance reboot, or the next failure reboot, whichever occurs first.
   *
   * @schema CacheClusterSpecForProvider#applyImmediately
   */
  readonly applyImmediately?: boolean;

  /**
   * The password used to access a password protected server.
   *
   * @schema CacheClusterSpecForProvider#authToken
   */
  readonly authToken?: string;

  /**
   * Specifies the strategy to use to update the AUTH token. This parameter must be specified with the auth-token parameter. Possible values:
   *
   * @schema CacheClusterSpecForProvider#authTokenUpdateStrategy
   */
  readonly authTokenUpdateStrategy?: string;

  /**
   * Specifies whether the nodes in this Memcached cluster are created in a single Availability Zone or created across multiple Availability Zones in the cluster's region. This parameter is only supported for Memcached clusters.
   *
   * @schema CacheClusterSpecForProvider#azMode
   */
  readonly azMode?: string;

  /**
   * A list of cache node IDs to be removed.
   *
   * @schema CacheClusterSpecForProvider#cacheNodeIdsToRemove
   */
  readonly cacheNodeIdsToRemove?: string[];

  /**
   * The compute and memory capacity of the nodes in the node group (shard).
   *
   * @schema CacheClusterSpecForProvider#cacheNodeType
   */
  readonly cacheNodeType: string;

  /**
   * The name of the parameter group to associate with this cluster. If this argument is omitted, the default parameter group for the specified engine is used.
   *
   * @schema CacheClusterSpecForProvider#cacheParameterGroupName
   */
  readonly cacheParameterGroupName?: string;

  /**
   * A list of security group names to associate with this cluster.
   *
   * @schema CacheClusterSpecForProvider#cacheSecurityGroupNames
   */
  readonly cacheSecurityGroupNames?: string[];

  /**
   * The name of the subnet group to be used for the cluster.
   *
   * @schema CacheClusterSpecForProvider#cacheSubnetGroupName
   */
  readonly cacheSubnetGroupName?: string;

  /**
   * A referencer to retrieve the name of a CacheSubnetGroup
   *
   * @schema CacheClusterSpecForProvider#cacheSubnetGroupNameRef
   */
  readonly cacheSubnetGroupNameRef?: CacheClusterSpecForProviderCacheSubnetGroupNameRef;

  /**
   * A selector to select a referencer to retrieve the name of a CacheSubnetGroup
   *
   * @schema CacheClusterSpecForProvider#cacheSubnetGroupNameSelector
   */
  readonly cacheSubnetGroupNameSelector?: CacheClusterSpecForProviderCacheSubnetGroupNameSelector;

  /**
   * The name of the cache engine to be used for this cluster.
   *
   * @schema CacheClusterSpecForProvider#engine
   */
  readonly engine?: string;

  /**
   * The version number of the cache engine to be used for this cluster.
   *
   * @schema CacheClusterSpecForProvider#engineVersion
   */
  readonly engineVersion?: string;

  /**
   * The Amazon Resource Name (ARN) of the Amazon Simple Notification Service (SNS) topic to which notifications are sent.
   *
   * @schema CacheClusterSpecForProvider#notificationTopicArn
   */
  readonly notificationTopicArn?: string;

  /**
   * The initial number of cache nodes that the cluster has.
   *
   * @schema CacheClusterSpecForProvider#numCacheNodes
   */
  readonly numCacheNodes: number;

  /**
   * The port number on which each of the cache nodes accepts connections.
   *
   * @schema CacheClusterSpecForProvider#port
   */
  readonly port?: number;

  /**
   * The EC2 Availability Zone in which the cluster is created. Default: System chosen Availability Zone.
   *
   * @schema CacheClusterSpecForProvider#preferredAvailabilityZone
   */
  readonly preferredAvailabilityZone?: string;

  /**
   * A list of the Availability Zones in which cache nodes are created.
   *
   * @schema CacheClusterSpecForProvider#preferredAvailabilityZones
   */
  readonly preferredAvailabilityZones?: string[];

  /**
   * Specifies the weekly time range during which maintenance on the cluster is performed.
   *
   * @schema CacheClusterSpecForProvider#preferredMaintenanceWindow
   */
  readonly preferredMaintenanceWindow?: string;

  /**
   * Region is the region you'd like your CacheSubnetGroup to be created in.
   *
   * @schema CacheClusterSpecForProvider#region
   */
  readonly region: string;

  /**
   * The ID of the replication group to which this cluster should belong.
   *
   * @schema CacheClusterSpecForProvider#replicationGroupId
   */
  readonly replicationGroupId?: string;

  /**
   * A referencer to retrieve the ID of a Security group
   *
   * @schema CacheClusterSpecForProvider#securityGroupIDRefs
   */
  readonly securityGroupIDRefs?: CacheClusterSpecForProviderSecurityGroupIdRefs[];

  /**
   * A selector to select a referencer to retrieve the ID of a Security Group
   *
   * @schema CacheClusterSpecForProvider#securityGroupIDSelector
   */
  readonly securityGroupIDSelector?: CacheClusterSpecForProviderSecurityGroupIdSelector;

  /**
   * One or more VPC security groups associated with the cluster.
   *
   * @schema CacheClusterSpecForProvider#securityGroupIds
   */
  readonly securityGroupIds?: string[];

  /**
   * A single-element string list containing an Amazon Resource Name (ARN) that uniquely identifies a Redis RDB snapshot file stored in Amazon S3.
   *
   * @schema CacheClusterSpecForProvider#snapshotArns
   */
  readonly snapshotArns?: string[];

  /**
   * The name of a Redis snapshot from which to restore data into the new node group (shard).
   *
   * @schema CacheClusterSpecForProvider#snapshotName
   */
  readonly snapshotName?: string;

  /**
   * The number of days for which ElastiCache retains automatic snapshots before deleting them.
   *
   * @schema CacheClusterSpecForProvider#snapshotRetentionLimit
   */
  readonly snapshotRetentionLimit?: number;

  /**
   * The daily time range (in UTC) during which ElastiCache begins taking a daily snapshot of your node group (shard).
   *
   * @schema CacheClusterSpecForProvider#snapshotWindow
   */
  readonly snapshotWindow?: string;

  /**
   * A list of cost allocation tags to be added to this resource.
   *
   * @schema CacheClusterSpecForProvider#tags
   */
  readonly tags?: CacheClusterSpecForProviderTags[];

}

/**
 * ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured.
 *
 * @schema CacheClusterSpecProviderConfigRef
 */
export interface CacheClusterSpecProviderConfigRef {
  /**
   * Name of the referenced object.
   *
   * @schema CacheClusterSpecProviderConfigRef#name
   */
  readonly name: string;

}

/**
 * ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`
 *
 * @schema CacheClusterSpecProviderRef
 */
export interface CacheClusterSpecProviderRef {
  /**
   * Name of the referenced object.
   *
   * @schema CacheClusterSpecProviderRef#name
   */
  readonly name: string;

}

/**
 * WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource.
 *
 * @schema CacheClusterSpecWriteConnectionSecretToRef
 */
export interface CacheClusterSpecWriteConnectionSecretToRef {
  /**
   * Name of the secret.
   *
   * @schema CacheClusterSpecWriteConnectionSecretToRef#name
   */
  readonly name: string;

  /**
   * Namespace of the secret.
   *
   * @schema CacheClusterSpecWriteConnectionSecretToRef#namespace
   */
  readonly namespace: string;

}

/**
 * A referencer to retrieve the name of a CacheSubnetGroup
 *
 * @schema CacheClusterSpecForProviderCacheSubnetGroupNameRef
 */
export interface CacheClusterSpecForProviderCacheSubnetGroupNameRef {
  /**
   * Name of the referenced object.
   *
   * @schema CacheClusterSpecForProviderCacheSubnetGroupNameRef#name
   */
  readonly name: string;

}

/**
 * A selector to select a referencer to retrieve the name of a CacheSubnetGroup
 *
 * @schema CacheClusterSpecForProviderCacheSubnetGroupNameSelector
 */
export interface CacheClusterSpecForProviderCacheSubnetGroupNameSelector {
  /**
   * MatchControllerRef ensures an object with the same controller reference as the selecting object is selected.
   *
   * @schema CacheClusterSpecForProviderCacheSubnetGroupNameSelector#matchControllerRef
   */
  readonly matchControllerRef?: boolean;

  /**
   * MatchLabels ensures an object with matching labels is selected.
   *
   * @schema CacheClusterSpecForProviderCacheSubnetGroupNameSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

}

/**
 * A Reference to a named object.
 *
 * @schema CacheClusterSpecForProviderSecurityGroupIdRefs
 */
export interface CacheClusterSpecForProviderSecurityGroupIdRefs {
  /**
   * Name of the referenced object.
   *
   * @schema CacheClusterSpecForProviderSecurityGroupIdRefs#name
   */
  readonly name: string;

}

/**
 * A selector to select a referencer to retrieve the ID of a Security Group
 *
 * @schema CacheClusterSpecForProviderSecurityGroupIdSelector
 */
export interface CacheClusterSpecForProviderSecurityGroupIdSelector {
  /**
   * MatchControllerRef ensures an object with the same controller reference as the selecting object is selected.
   *
   * @schema CacheClusterSpecForProviderSecurityGroupIdSelector#matchControllerRef
   */
  readonly matchControllerRef?: boolean;

  /**
   * MatchLabels ensures an object with matching labels is selected.
   *
   * @schema CacheClusterSpecForProviderSecurityGroupIdSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

}

/**
 * A Tag is used to tag the ElastiCache resources in AWS.
 *
 * @schema CacheClusterSpecForProviderTags
 */
export interface CacheClusterSpecForProviderTags {
  /**
   * Key for the tag.
   *
   * @schema CacheClusterSpecForProviderTags#key
   */
  readonly key: string;

  /**
   * Value of the tag.
   *
   * @schema CacheClusterSpecForProviderTags#value
   */
  readonly value?: string;

}

/**
 * A CacheSubnetGroup is a managed resource that represents an AWS Subnet Group for ElasticCache.
 *
 * @schema CacheSubnetGroup
 */
export class CacheSubnetGroup extends ApiObject {
  /**
   * Defines a "CacheSubnetGroup" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialiation props
   */
  public constructor(scope: Construct, id: string, props: CacheSubnetGroupProps) {
    super(scope, id, {
      ...props,
      kind: 'CacheSubnetGroup',
      apiVersion: 'cache.aws.crossplane.io/v1alpha1',
    });
  }
}

/**
 * A CacheSubnetGroup is a managed resource that represents an AWS Subnet Group for ElasticCache.
 *
 * @schema CacheSubnetGroup
 */
export interface CacheSubnetGroupProps {
  /**
   * @schema CacheSubnetGroup#metadata
   */
  readonly metadata?: any;

  /**
   * A CacheSubnetGroupSpec defines the desired state of a CacheSubnetGroup.
   *
   * @schema CacheSubnetGroup#spec
   */
  readonly spec: CacheSubnetGroupSpec;

}

/**
 * A CacheSubnetGroupSpec defines the desired state of a CacheSubnetGroup.
 *
 * @schema CacheSubnetGroupSpec
 */
export interface CacheSubnetGroupSpec {
  /**
   * DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource. The "Delete" policy is the default when no policy is specified.
   *
   * @schema CacheSubnetGroupSpec#deletionPolicy
   */
  readonly deletionPolicy?: CacheSubnetGroupSpecDeletionPolicy;

  /**
   * CacheSubnetGroupParameters define the desired state of an AWS ElasticCache Subnet Group.
   *
   * @schema CacheSubnetGroupSpec#forProvider
   */
  readonly forProvider: CacheSubnetGroupSpecForProvider;

  /**
   * ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured.
   *
   * @schema CacheSubnetGroupSpec#providerConfigRef
   */
  readonly providerConfigRef?: CacheSubnetGroupSpecProviderConfigRef;

  /**
   * ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`
   *
   * @schema CacheSubnetGroupSpec#providerRef
   */
  readonly providerRef?: CacheSubnetGroupSpecProviderRef;

  /**
   * WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource.
   *
   * @schema CacheSubnetGroupSpec#writeConnectionSecretToRef
   */
  readonly writeConnectionSecretToRef?: CacheSubnetGroupSpecWriteConnectionSecretToRef;

}

/**
 * DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource. The "Delete" policy is the default when no policy is specified.
 *
 * @schema CacheSubnetGroupSpecDeletionPolicy
 */
export enum CacheSubnetGroupSpecDeletionPolicy {
  /** Orphan */
  ORPHAN = "Orphan",
  /** Delete */
  DELETE = "Delete",
}

/**
 * CacheSubnetGroupParameters define the desired state of an AWS ElasticCache Subnet Group.
 *
 * @schema CacheSubnetGroupSpecForProvider
 */
export interface CacheSubnetGroupSpecForProvider {
  /**
   * A description for the cache subnet group.
   *
   * @schema CacheSubnetGroupSpecForProvider#description
   */
  readonly description: string;

  /**
   * Region is the region you'd like your CacheSubnetGroup to be created in.
   *
   * @schema CacheSubnetGroupSpecForProvider#region
   */
  readonly region: string;

  /**
   * SubnetIDRefs references to a Subnet to and retrieves its SubnetID
   *
   * @schema CacheSubnetGroupSpecForProvider#subnetIdRefs
   */
  readonly subnetIdRefs?: CacheSubnetGroupSpecForProviderSubnetIdRefs[];

  /**
   * SubnetIDSelector selects a set of references that each retrieve the subnetID from the referenced Subnet
   *
   * @schema CacheSubnetGroupSpecForProvider#subnetIdSelector
   */
  readonly subnetIdSelector?: CacheSubnetGroupSpecForProviderSubnetIdSelector;

  /**
   * A list of  Subnet IDs for the cache subnet group.
   *
   * @schema CacheSubnetGroupSpecForProvider#subnetIds
   */
  readonly subnetIds?: string[];

}

/**
 * ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured.
 *
 * @schema CacheSubnetGroupSpecProviderConfigRef
 */
export interface CacheSubnetGroupSpecProviderConfigRef {
  /**
   * Name of the referenced object.
   *
   * @schema CacheSubnetGroupSpecProviderConfigRef#name
   */
  readonly name: string;

}

/**
 * ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`
 *
 * @schema CacheSubnetGroupSpecProviderRef
 */
export interface CacheSubnetGroupSpecProviderRef {
  /**
   * Name of the referenced object.
   *
   * @schema CacheSubnetGroupSpecProviderRef#name
   */
  readonly name: string;

}

/**
 * WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource.
 *
 * @schema CacheSubnetGroupSpecWriteConnectionSecretToRef
 */
export interface CacheSubnetGroupSpecWriteConnectionSecretToRef {
  /**
   * Name of the secret.
   *
   * @schema CacheSubnetGroupSpecWriteConnectionSecretToRef#name
   */
  readonly name: string;

  /**
   * Namespace of the secret.
   *
   * @schema CacheSubnetGroupSpecWriteConnectionSecretToRef#namespace
   */
  readonly namespace: string;

}

/**
 * A Reference to a named object.
 *
 * @schema CacheSubnetGroupSpecForProviderSubnetIdRefs
 */
export interface CacheSubnetGroupSpecForProviderSubnetIdRefs {
  /**
   * Name of the referenced object.
   *
   * @schema CacheSubnetGroupSpecForProviderSubnetIdRefs#name
   */
  readonly name: string;

}

/**
 * SubnetIDSelector selects a set of references that each retrieve the subnetID from the referenced Subnet
 *
 * @schema CacheSubnetGroupSpecForProviderSubnetIdSelector
 */
export interface CacheSubnetGroupSpecForProviderSubnetIdSelector {
  /**
   * MatchControllerRef ensures an object with the same controller reference as the selecting object is selected.
   *
   * @schema CacheSubnetGroupSpecForProviderSubnetIdSelector#matchControllerRef
   */
  readonly matchControllerRef?: boolean;

  /**
   * MatchLabels ensures an object with matching labels is selected.
   *
   * @schema CacheSubnetGroupSpecForProviderSubnetIdSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

}

/**
 * A ReplicationGroup is a managed resource that represents an AWS ElastiCache Replication Group.
 *
 * @schema ReplicationGroup
 */
export class ReplicationGroup extends ApiObject {
  /**
   * Defines a "ReplicationGroup" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialiation props
   */
  public constructor(scope: Construct, id: string, props: ReplicationGroupProps) {
    super(scope, id, {
      ...props,
      kind: 'ReplicationGroup',
      apiVersion: 'cache.aws.crossplane.io/v1beta1',
    });
  }
}

/**
 * A ReplicationGroup is a managed resource that represents an AWS ElastiCache Replication Group.
 *
 * @schema ReplicationGroup
 */
export interface ReplicationGroupProps {
  /**
   * @schema ReplicationGroup#metadata
   */
  readonly metadata?: any;

  /**
   * A ReplicationGroupSpec defines the desired state of a ReplicationGroup.
   *
   * @schema ReplicationGroup#spec
   */
  readonly spec: ReplicationGroupSpec;

}

/**
 * A ReplicationGroupSpec defines the desired state of a ReplicationGroup.
 *
 * @schema ReplicationGroupSpec
 */
export interface ReplicationGroupSpec {
  /**
   * DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource. The "Delete" policy is the default when no policy is specified.
   *
   * @schema ReplicationGroupSpec#deletionPolicy
   */
  readonly deletionPolicy?: ReplicationGroupSpecDeletionPolicy;

  /**
   * ReplicationGroupParameters define the desired state of an AWS ElastiCache Replication Group. Most fields map directly to an AWS ReplicationGroup: https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateReplicationGroup.html#API_CreateReplicationGroup_RequestParameters
   *
   * @schema ReplicationGroupSpec#forProvider
   */
  readonly forProvider: ReplicationGroupSpecForProvider;

  /**
   * ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured.
   *
   * @schema ReplicationGroupSpec#providerConfigRef
   */
  readonly providerConfigRef?: ReplicationGroupSpecProviderConfigRef;

  /**
   * ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`
   *
   * @schema ReplicationGroupSpec#providerRef
   */
  readonly providerRef?: ReplicationGroupSpecProviderRef;

  /**
   * WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource.
   *
   * @schema ReplicationGroupSpec#writeConnectionSecretToRef
   */
  readonly writeConnectionSecretToRef?: ReplicationGroupSpecWriteConnectionSecretToRef;

}

/**
 * DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource. The "Delete" policy is the default when no policy is specified.
 *
 * @schema ReplicationGroupSpecDeletionPolicy
 */
export enum ReplicationGroupSpecDeletionPolicy {
  /** Orphan */
  ORPHAN = "Orphan",
  /** Delete */
  DELETE = "Delete",
}

/**
 * ReplicationGroupParameters define the desired state of an AWS ElastiCache Replication Group. Most fields map directly to an AWS ReplicationGroup: https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateReplicationGroup.html#API_CreateReplicationGroup_RequestParameters
 *
 * @schema ReplicationGroupSpecForProvider
 */
export interface ReplicationGroupSpecForProvider {
  /**
   * If true, this parameter causes the modifications in this request and any pending modifications to be applied, asynchronously and as soon as possible, regardless of the PreferredMaintenanceWindow setting for the replication group. 
 If false, changes to the nodes in the replication group are applied on the next maintenance reboot, or the next failure reboot, whichever occurs first.
   *
   * @schema ReplicationGroupSpecForProvider#applyModificationsImmediately
   */
  readonly applyModificationsImmediately: boolean;

  /**
   * AtRestEncryptionEnabled enables encryption at rest when set to true. 
 You cannot modify the value of AtRestEncryptionEnabled after the replication group is created. To enable encryption at rest on a replication group you must set AtRestEncryptionEnabled to true when you create the replication group. 
 Only available when creating a replication group in an Amazon VPC using redis version 3.2.6 or 4.x.
   *
   * @schema ReplicationGroupSpecForProvider#atRestEncryptionEnabled
   */
  readonly atRestEncryptionEnabled?: boolean;

  /**
   * AuthEnabled enables mandatory authentication when connecting to the managed replication group. AuthEnabled requires TransitEncryptionEnabled to be true. 
 While ReplicationGroupSpec mirrors the fields of the upstream replication group object as closely as possible, we expose a boolean here rather than requiring the operator pass in a string authentication token. Crossplane will generate a token automatically and expose it via a Secret.
   *
   * @schema ReplicationGroupSpecForProvider#authEnabled
   */
  readonly authEnabled?: boolean;

  /**
   * AutomaticFailoverEnabled specifies whether a read-only replica is automatically promoted to read/write primary if the existing primary fails. If true, Multi-AZ is enabled for this replication group. If false, Multi-AZ is disabled for this replication group. 
 AutomaticFailoverEnabled must be enabled for Redis (cluster mode enabled) replication groups. 
 Amazon ElastiCache for Redis does not support Multi-AZ with automatic failover on: * Redis versions earlier than 2.8.6. * Redis (cluster mode disabled): T1 and T2 cache node types. * Redis (cluster mode enabled): T1 node types.
   *
   * @schema ReplicationGroupSpecForProvider#automaticFailoverEnabled
   */
  readonly automaticFailoverEnabled?: boolean;

  /**
   * CacheNodeType specifies the compute and memory capacity of the nodes in the node group (shard). For a complete listing of node types and specifications, see: * Amazon ElastiCache Product Features and Details (http://aws.amazon.com/elasticache/details) * Cache Node Type-Specific Parameters for Memcached (http://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/ParameterGroups.Memcached.html#ParameterGroups.Memcached.NodeSpecific) * Cache Node Type-Specific Parameters for Redis (http://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/ParameterGroups.Redis.html#ParameterGroups.Redis.NodeSpecific)
   *
   * @schema ReplicationGroupSpecForProvider#cacheNodeType
   */
  readonly cacheNodeType: string;

  /**
   * CacheParameterGroupName specifies the name of the parameter group to associate with this replication group. If this argument is omitted, the default cache parameter group for the specified engine is used. 
 If you are running Redis version 3.2.4 or later, only one node group (shard), and want to use a default parameter group, we recommend that you specify the parameter group by name. * To create a Redis (cluster mode disabled) replication group, use CacheParameterGroupName=default.redis3.2. * To create a Redis (cluster mode enabled) replication group, use CacheParameterGroupName=default.redis3.2.cluster.on.
   *
   * @schema ReplicationGroupSpecForProvider#cacheParameterGroupName
   */
  readonly cacheParameterGroupName?: string;

  /**
   * CacheSecurityGroupNameRefs are references to SecurityGroups used to set the CacheSecurityGroupNames.
   *
   * @schema ReplicationGroupSpecForProvider#cacheSecurityGroupNameRefs
   */
  readonly cacheSecurityGroupNameRefs?: ReplicationGroupSpecForProviderCacheSecurityGroupNameRefs[];

  /**
   * CacheSecurityGroupNameSelector selects references to SecurityGroups.
   *
   * @schema ReplicationGroupSpecForProvider#cacheSecurityGroupNameSelector
   */
  readonly cacheSecurityGroupNameSelector?: ReplicationGroupSpecForProviderCacheSecurityGroupNameSelector;

  /**
   * CacheSecurityGroupNames specifies a list of cache security group names to associate with this replication group. Only for EC2-Classic mode.
   *
   * @schema ReplicationGroupSpecForProvider#cacheSecurityGroupNames
   */
  readonly cacheSecurityGroupNames?: string[];

  /**
   * CacheSubnetGroupName specifies the name of the cache subnet group to be used for the replication group. If you're going to launch your cluster in an Amazon VPC, you need to create a subnet group before you start creating a cluster. For more information, see Subnets and Subnet Groups (http://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/SubnetGroups.html).
   *
   * @schema ReplicationGroupSpecForProvider#cacheSubnetGroupName
   */
  readonly cacheSubnetGroupName?: string;

  /**
   * CacheSubnetGroupNameRef is a reference to a Subnet Group the CacheSubnetGroupName.
   *
   * @schema ReplicationGroupSpecForProvider#cacheSubnetGroupNameRefs
   */
  readonly cacheSubnetGroupNameRefs?: ReplicationGroupSpecForProviderCacheSubnetGroupNameRefs;

  /**
   * CacheSubnetGroupNameSelector selects a reference to a CacheSubnetGroup.
   *
   * @schema ReplicationGroupSpecForProvider#cacheSubnetGroupNameSelector
   */
  readonly cacheSubnetGroupNameSelector?: ReplicationGroupSpecForProviderCacheSubnetGroupNameSelector;

  /**
   * Engine is the name of the cache engine (memcached or redis) to be used for the clusters in this replication group.
   *
   * @schema ReplicationGroupSpecForProvider#engine
   */
  readonly engine: string;

  /**
   * EngineVersion specifies the version number of the cache engine to be used for the clusters in this replication group. To view the supported cache engine versions, use the DescribeCacheEngineVersions operation. 
 Important: You can upgrade to a newer engine version (see Selecting a Cache Engine and Version (http://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/SelectEngine.html#VersionManagement)) in the ElastiCache User Guide, but you cannot downgrade to an earlier engine version. If you want to use an earlier engine version, you must delete the existing cluster or replication group and create it anew with the earlier engine version.
   *
   * @schema ReplicationGroupSpecForProvider#engineVersion
   */
  readonly engineVersion?: string;

  /**
   * NodeGroupConfigurationSpec specifies a list of node group (shard) configuration options. 
 If you're creating a Redis (cluster mode disabled) or a Redis (cluster mode enabled) replication group, you can use this parameter to individually configure each node group (shard), or you can omit this parameter. However, when seeding a Redis (cluster mode enabled) cluster from a S3 rdb file, you must configure each node group (shard) using this parameter because you must specify the slots for each node group.
   *
   * @schema ReplicationGroupSpecForProvider#nodeGroupConfiguration
   */
  readonly nodeGroupConfiguration?: ReplicationGroupSpecForProviderNodeGroupConfiguration[];

  /**
   * NotificationTopicARN specifies the Amazon Resource Name (ARN) of the Amazon Simple Notification Service (SNS) topic to which notifications are sent. The Amazon SNS topic owner must be the same as the cluster owner.
   *
   * @schema ReplicationGroupSpecForProvider#notificationTopicArn
   */
  readonly notificationTopicArn?: string;

  /**
   * NotificationTopicStatus is the status of the Amazon SNS notification topic for the replication group. Notifications are sent only if the status is active. 
 Valid values: active | inactive
   *
   * @schema ReplicationGroupSpecForProvider#notificationTopicStatus
   */
  readonly notificationTopicStatus?: string;

  /**
   * NumCacheClusters specifies the number of clusters this replication group initially has. This parameter is not used if there is more than one node group (shard). You should use ReplicasPerNodeGroup instead. 
 If AutomaticFailoverEnabled is true, the value of this parameter must be at least 2. If AutomaticFailoverEnabled is false you can omit this parameter (it will default to 1), or you can explicitly set it to a value between 2 and 6. 
 The maximum permitted value for NumCacheClusters is 6 (1 primary plus 5 replicas).
   *
   * @schema ReplicationGroupSpecForProvider#numCacheClusters
   */
  readonly numCacheClusters?: number;

  /**
   * NumNodeGroups specifies the number of node groups (shards) for this Redis (cluster mode enabled) replication group. For Redis (cluster mode disabled) either omit this parameter or set it to 1. 
 Default: 1
   *
   * @schema ReplicationGroupSpecForProvider#numNodeGroups
   */
  readonly numNodeGroups?: number;

  /**
   * Port number on which each member of the replication group accepts connections.
   *
   * @schema ReplicationGroupSpecForProvider#port
   */
  readonly port?: number;

  /**
   * PreferredCacheClusterAZs specifies a list of EC2 Availability Zones in which the replication group's clusters are created. The order of the Availability Zones in the list is the order in which clusters are allocated. The primary cluster is created in the first AZ in the list. 
 This parameter is not used if there is more than one node group (shard). You should use NodeGroupConfigurationSpec instead. 
 If you are creating your replication group in an Amazon VPC (recommended), you can only locate clusters in Availability Zones associated with the subnets in the selected subnet group. 
 The number of Availability Zones listed must equal the value of NumCacheClusters. 
 Default: system chosen Availability Zones.
   *
   * @schema ReplicationGroupSpecForProvider#preferredCacheClusterAzs
   */
  readonly preferredCacheClusterAzs?: string[];

  /**
   * PreferredMaintenanceWindow specifies the weekly time range during which maintenance on the cluster is performed. It is specified as a range in the format ddd:hh24:mi-ddd:hh24:mi (24H Clock UTC). The minimum maintenance window is a 60 minute period. 
 Example: sun:23:00-mon:01:30
   *
   * @schema ReplicationGroupSpecForProvider#preferredMaintenanceWindow
   */
  readonly preferredMaintenanceWindow?: string;

  /**
   * PrimaryClusterId is the identifier of the cluster that serves as the primary for this replication group. This cluster must already exist and have a status of available. 
 This parameter is not required if NumCacheClusters, NumNodeGroups or ReplicasPerNodeGroup is specified.
   *
   * @schema ReplicationGroupSpecForProvider#primaryClusterId
   */
  readonly primaryClusterId?: string;

  /**
   * Region is the region you'd like your ReplicationGroup to be created in.
   *
   * @schema ReplicationGroupSpecForProvider#region
   */
  readonly region?: string;

  /**
   * ReplicasPerNodeGroup specifies the number of replica nodes in each node group (shard). Valid values are 0 to 5.
   *
   * @schema ReplicationGroupSpecForProvider#replicasPerNodeGroup
   */
  readonly replicasPerNodeGroup?: number;

  /**
   * ReplicationGroupDescription is the description for the replication group.
   *
   * @schema ReplicationGroupSpecForProvider#replicationGroupDescription
   */
  readonly replicationGroupDescription: string;

  /**
   * SecurityGroupIDRefs are references to SecurityGroups used to set the SecurityGroupIDs.
   *
   * @schema ReplicationGroupSpecForProvider#securityGroupIdRefs
   */
  readonly securityGroupIdRefs?: ReplicationGroupSpecForProviderSecurityGroupIdRefs[];

  /**
   * SecurityGroupIDSelector selects references to SecurityGroups used to set the SecurityGroupIDs.
   *
   * @schema ReplicationGroupSpecForProvider#securityGroupIdSelector
   */
  readonly securityGroupIdSelector?: ReplicationGroupSpecForProviderSecurityGroupIdSelector;

  /**
   * SecurityGroupIDs specifies one or more Amazon VPC security groups associated with this replication group. Use this parameter only when you are creating a replication group in an Amazon VPC.
   *
   * @schema ReplicationGroupSpecForProvider#securityGroupIds
   */
  readonly securityGroupIds?: string[];

  /**
   * SnapshotARNs specifies a list of Amazon Resource Names (ARN) that uniquely identify the Redis RDB snapshot files stored in Amazon S3. The snapshot files are used to populate the new replication group. The Amazon S3 object name in the ARN cannot contain any commas. The new replication group will have the number of node groups (console: shards) specified by the parameter NumNodeGroups or the number of node groups configured by NodeGroupConfigurationSpec regardless of the number of ARNs specified here.
   *
   * @schema ReplicationGroupSpecForProvider#snapshotArns
   */
  readonly snapshotArns?: string[];

  /**
   * SnapshotName specifies the name of a snapshot from which to restore data into the new replication group. The snapshot status changes to restoring while the new replication group is being created.
   *
   * @schema ReplicationGroupSpecForProvider#snapshotName
   */
  readonly snapshotName?: string;

  /**
   * SnapshotRetentionLimit specifies the number of days for which ElastiCache retains automatic snapshots before deleting them. For example, if you set SnapshotRetentionLimit to 5, a snapshot that was taken today is retained for 5 days before being deleted. Default: 0 (i.e., automatic backups are disabled for this cluster).
   *
   * @schema ReplicationGroupSpecForProvider#snapshotRetentionLimit
   */
  readonly snapshotRetentionLimit?: number;

  /**
   * SnapshotWindow specifies the daily time range (in UTC) during which ElastiCache begins taking a daily snapshot of your node group (shard). 
 Example: 05:00-09:00 
 If you do not specify this parameter, ElastiCache automatically chooses an appropriate time range.
   *
   * @schema ReplicationGroupSpecForProvider#snapshotWindow
   */
  readonly snapshotWindow?: string;

  /**
   * SnapshottingClusterID is used as the daily snapshot source for the replication group. This parameter cannot be set for Redis (cluster mode enabled) replication groups.
   *
   * @schema ReplicationGroupSpecForProvider#snapshottingClusterID
   */
  readonly snapshottingClusterID?: string;

  /**
   * A list of cost allocation tags to be added to this resource. A tag is a key-value pair.
   *
   * @schema ReplicationGroupSpecForProvider#tags
   */
  readonly tags?: ReplicationGroupSpecForProviderTags[];

  /**
   * TransitEncryptionEnabled enables in-transit encryption when set to true. 
 You cannot modify the value of TransitEncryptionEnabled after the cluster is created. To enable in-transit encryption on a cluster you must TransitEncryptionEnabled to true when you create a cluster. 
 This parameter is valid only if the Engine parameter is redis, the EngineVersion parameter is 3.2.6 or 4.x, and the cluster is being created in an Amazon VPC. 
 If you enable in-transit encryption, you must also specify a value for CacheSubnetGroup. 
 Required: Only available when creating a replication group in an Amazon VPC using redis version 3.2.6 or 4.x. 
 Default: false 
 For HIPAA compliance, you must specify TransitEncryptionEnabled as true, an AuthToken, and a CacheSubnetGroup.
   *
   * @schema ReplicationGroupSpecForProvider#transitEncryptionEnabled
   */
  readonly transitEncryptionEnabled?: boolean;

}

/**
 * ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured.
 *
 * @schema ReplicationGroupSpecProviderConfigRef
 */
export interface ReplicationGroupSpecProviderConfigRef {
  /**
   * Name of the referenced object.
   *
   * @schema ReplicationGroupSpecProviderConfigRef#name
   */
  readonly name: string;

}

/**
 * ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`
 *
 * @schema ReplicationGroupSpecProviderRef
 */
export interface ReplicationGroupSpecProviderRef {
  /**
   * Name of the referenced object.
   *
   * @schema ReplicationGroupSpecProviderRef#name
   */
  readonly name: string;

}

/**
 * WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource.
 *
 * @schema ReplicationGroupSpecWriteConnectionSecretToRef
 */
export interface ReplicationGroupSpecWriteConnectionSecretToRef {
  /**
   * Name of the secret.
   *
   * @schema ReplicationGroupSpecWriteConnectionSecretToRef#name
   */
  readonly name: string;

  /**
   * Namespace of the secret.
   *
   * @schema ReplicationGroupSpecWriteConnectionSecretToRef#namespace
   */
  readonly namespace: string;

}

/**
 * A Reference to a named object.
 *
 * @schema ReplicationGroupSpecForProviderCacheSecurityGroupNameRefs
 */
export interface ReplicationGroupSpecForProviderCacheSecurityGroupNameRefs {
  /**
   * Name of the referenced object.
   *
   * @schema ReplicationGroupSpecForProviderCacheSecurityGroupNameRefs#name
   */
  readonly name: string;

}

/**
 * CacheSecurityGroupNameSelector selects references to SecurityGroups.
 *
 * @schema ReplicationGroupSpecForProviderCacheSecurityGroupNameSelector
 */
export interface ReplicationGroupSpecForProviderCacheSecurityGroupNameSelector {
  /**
   * MatchControllerRef ensures an object with the same controller reference as the selecting object is selected.
   *
   * @schema ReplicationGroupSpecForProviderCacheSecurityGroupNameSelector#matchControllerRef
   */
  readonly matchControllerRef?: boolean;

  /**
   * MatchLabels ensures an object with matching labels is selected.
   *
   * @schema ReplicationGroupSpecForProviderCacheSecurityGroupNameSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

}

/**
 * CacheSubnetGroupNameRef is a reference to a Subnet Group the CacheSubnetGroupName.
 *
 * @schema ReplicationGroupSpecForProviderCacheSubnetGroupNameRefs
 */
export interface ReplicationGroupSpecForProviderCacheSubnetGroupNameRefs {
  /**
   * Name of the referenced object.
   *
   * @schema ReplicationGroupSpecForProviderCacheSubnetGroupNameRefs#name
   */
  readonly name: string;

}

/**
 * CacheSubnetGroupNameSelector selects a reference to a CacheSubnetGroup.
 *
 * @schema ReplicationGroupSpecForProviderCacheSubnetGroupNameSelector
 */
export interface ReplicationGroupSpecForProviderCacheSubnetGroupNameSelector {
  /**
   * MatchControllerRef ensures an object with the same controller reference as the selecting object is selected.
   *
   * @schema ReplicationGroupSpecForProviderCacheSubnetGroupNameSelector#matchControllerRef
   */
  readonly matchControllerRef?: boolean;

  /**
   * MatchLabels ensures an object with matching labels is selected.
   *
   * @schema ReplicationGroupSpecForProviderCacheSubnetGroupNameSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

}

/**
 * A NodeGroupConfigurationSpec specifies the desired state of a node group.
 *
 * @schema ReplicationGroupSpecForProviderNodeGroupConfiguration
 */
export interface ReplicationGroupSpecForProviderNodeGroupConfiguration {
  /**
   * PrimaryAvailabilityZone specifies the Availability Zone where the primary node of this node group (shard) is launched.
   *
   * @schema ReplicationGroupSpecForProviderNodeGroupConfiguration#primaryAvailabilityZone
   */
  readonly primaryAvailabilityZone?: string;

  /**
   * ReplicaAvailabilityZones specifies a list of Availability Zones to be used for the read replicas. The number of Availability Zones in this list must match the value of ReplicaCount or ReplicasPerNodeGroup if not specified.
   *
   * @schema ReplicationGroupSpecForProviderNodeGroupConfiguration#replicaAvailabilityZones
   */
  readonly replicaAvailabilityZones?: string[];

  /**
   * ReplicaCount specifies the number of read replica nodes in this node group (shard).
   *
   * @schema ReplicationGroupSpecForProviderNodeGroupConfiguration#replicaCount
   */
  readonly replicaCount?: number;

  /**
   * Slots specifies the keyspace for a particular node group. Keyspaces range from 0 to 16,383. The string is in the format startkey-endkey. 
 Example: "0-3999"
   *
   * @schema ReplicationGroupSpecForProviderNodeGroupConfiguration#slots
   */
  readonly slots?: string;

}

/**
 * A Reference to a named object.
 *
 * @schema ReplicationGroupSpecForProviderSecurityGroupIdRefs
 */
export interface ReplicationGroupSpecForProviderSecurityGroupIdRefs {
  /**
   * Name of the referenced object.
   *
   * @schema ReplicationGroupSpecForProviderSecurityGroupIdRefs#name
   */
  readonly name: string;

}

/**
 * SecurityGroupIDSelector selects references to SecurityGroups used to set the SecurityGroupIDs.
 *
 * @schema ReplicationGroupSpecForProviderSecurityGroupIdSelector
 */
export interface ReplicationGroupSpecForProviderSecurityGroupIdSelector {
  /**
   * MatchControllerRef ensures an object with the same controller reference as the selecting object is selected.
   *
   * @schema ReplicationGroupSpecForProviderSecurityGroupIdSelector#matchControllerRef
   */
  readonly matchControllerRef?: boolean;

  /**
   * MatchLabels ensures an object with matching labels is selected.
   *
   * @schema ReplicationGroupSpecForProviderSecurityGroupIdSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

}

/**
 * A Tag is used to tag the ElastiCache resources in AWS.
 *
 * @schema ReplicationGroupSpecForProviderTags
 */
export interface ReplicationGroupSpecForProviderTags {
  /**
   * Key for the tag.
   *
   * @schema ReplicationGroupSpecForProviderTags#key
   */
  readonly key: string;

  /**
   * Value of the tag.
   *
   * @schema ReplicationGroupSpecForProviderTags#value
   */
  readonly value: string;

}

