// generated by cdk8s
import { ApiObject } from 'cdk8s';
import { Construct } from 'constructs';

/**
 * SNSTopic defines a managed resource that represents state of a AWS SNSTopic
 *
 * @schema SNSTopic
 */
export class SnsTopic extends ApiObject {
  /**
   * Defines a "SNSTopic" API object
   * @param scope the scope in which to define this object
   * @param name a scope-local name for the object
   * @param options configuration options
   */
  public constructor(scope: Construct, name: string, options: SnsTopicOptions) {
    super(scope, name, {
      ...options,
      kind: 'SNSTopic',
      apiVersion: 'notification.aws.crossplane.io/v1alpha1',
    });
  }
}

/**
 * SNSTopic defines a managed resource that represents state of a AWS SNSTopic
 *
 * @schema SNSTopic
 */
export interface SnsTopicOptions {
  /**
   * @schema SNSTopic#metadata
   */
  readonly metadata?: any;

  /**
   * SNSTopicSpec defined the desired state of a AWS SNS Topic
   *
   * @schema SNSTopic#spec
   */
  readonly spec: SnsTopicSpec;

}

/**
 * SNSTopicSpec defined the desired state of a AWS SNS Topic
 *
 * @schema SnsTopicSpec
 */
export interface SnsTopicSpec {
  /**
   * DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource. The "Delete" policy is the default when no policy is specified.
   *
   * @schema SnsTopicSpec#deletionPolicy
   */
  readonly deletionPolicy?: SnsTopicSpecDeletionPolicy;

  /**
   * SNSTopicParameters define the desired state of a AWS SNS Topic
   *
   * @schema SnsTopicSpec#forProvider
   */
  readonly forProvider: SnsTopicSpecForProvider;

  /**
   * ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured.
   *
   * @schema SnsTopicSpec#providerConfigRef
   */
  readonly providerConfigRef?: SnsTopicSpecProviderConfigRef;

  /**
   * ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`
   *
   * @schema SnsTopicSpec#providerRef
   */
  readonly providerRef?: SnsTopicSpecProviderRef;

  /**
   * WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource.
   *
   * @schema SnsTopicSpec#writeConnectionSecretToRef
   */
  readonly writeConnectionSecretToRef?: SnsTopicSpecWriteConnectionSecretToRef;

}

/**
 * DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource. The "Delete" policy is the default when no policy is specified.
 *
 * @schema SnsTopicSpecDeletionPolicy
 */
export enum SnsTopicSpecDeletionPolicy {
  /** Orphan */
  ORPHAN = 'Orphan',
  /** Delete */
  DELETE = 'Delete',
}

/**
 * SNSTopicParameters define the desired state of a AWS SNS Topic
 *
 * @schema SnsTopicSpecForProvider
 */
export interface SnsTopicSpecForProvider {
  /**
   * DeliveryRetryPolicy - the JSON serialization of the effective delivery policy, taking system defaults into account
   *
   * @schema SnsTopicSpecForProvider#deliveryPolicy
   */
  readonly deliveryPolicy?: string;

  /**
   * The display name to use for a topic with SNS subscriptions.
   *
   * @schema SnsTopicSpecForProvider#displayName
   */
  readonly displayName?: string;

  /**
   * Setting this enables server side encryption at-rest to your topic. The ID of an AWS-managed customer master key (CMK) for Amazon SNS or a custom CMK
 For more examples, see KeyId (https://docs.aws.amazon.com/kms/latest/APIReference/API_DescribeKey.html#API_DescribeKey_RequestParameters) in the AWS Key Management Service API Reference.
   *
   * @schema SnsTopicSpecForProvider#kmsMasterKeyId
   */
  readonly kmsMasterKeyId?: string;

  /**
   * Name refers to the name of the AWS SNS Topic
   *
   * @schema SnsTopicSpecForProvider#name
   */
  readonly name: string;

  /**
   * The policy that defines who can access your topic. By default, only the topic owner can publish or subscribe to the topic.
   *
   * @schema SnsTopicSpecForProvider#policy
   */
  readonly policy?: string;

  /**
   * Region is the region you'd like your SNSTopic to be created in.
   *
   * @schema SnsTopicSpecForProvider#region
   */
  readonly region: string;

  /**
   * Tags represetnt a list of user-provided metadata that can be associated with a SNS Topic. For more information about tagging, see Tagging SNS Topics (https://docs.aws.amazon.com/sns/latest/dg/sns-tags.html) in the SNS User Guide.
   *
   * @schema SnsTopicSpecForProvider#tags
   */
  readonly tags?: SnsTopicSpecForProviderTags[];

}

/**
 * ProviderConfigReference specifies how the provider that will be used to create, observe, update, and delete this managed resource should be configured.
 *
 * @schema SnsTopicSpecProviderConfigRef
 */
export interface SnsTopicSpecProviderConfigRef {
  /**
   * Name of the referenced object.
   *
   * @schema SnsTopicSpecProviderConfigRef#name
   */
  readonly name: string;

}

/**
 * ProviderReference specifies the provider that will be used to create, observe, update, and delete this managed resource. Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`
 *
 * @schema SnsTopicSpecProviderRef
 */
export interface SnsTopicSpecProviderRef {
  /**
   * Name of the referenced object.
   *
   * @schema SnsTopicSpecProviderRef#name
   */
  readonly name: string;

}

/**
 * WriteConnectionSecretToReference specifies the namespace and name of a Secret to which any connection details for this managed resource should be written. Connection details frequently include the endpoint, username, and password required to connect to the managed resource.
 *
 * @schema SnsTopicSpecWriteConnectionSecretToRef
 */
export interface SnsTopicSpecWriteConnectionSecretToRef {
  /**
   * Name of the secret.
   *
   * @schema SnsTopicSpecWriteConnectionSecretToRef#name
   */
  readonly name: string;

  /**
   * Namespace of the secret.
   *
   * @schema SnsTopicSpecWriteConnectionSecretToRef#namespace
   */
  readonly namespace: string;

}

/**
 * Tag represent a user-provided metadata that can be associated with a SNS Topic. For more information about tagging, see Tagging SNS Topics (https://docs.aws.amazon.com/sns/latest/dg/sns-tags.html) in the SNS User Guide.
 *
 * @schema SnsTopicSpecForProviderTags
 */
export interface SnsTopicSpecForProviderTags {
  /**
   * The key name that can be used to look up or retrieve the associated value. For example, Department or Cost Center are common choices.
   *
   * @schema SnsTopicSpecForProviderTags#key
   */
  readonly key: string;

  /**
   * The value associated with this tag. For example, tags with a key name of Department could have values such as Human Resources, Accounting, and Support. Tags with a key name of Cost Center might have values that consist of the number associated with the different cost centers in your company. Typically, many resources have tags with the same key name but with different values.
 AWS always interprets the tag Value as a single string. If you need to store an array, you can store comma-separated values in the string. However, you must interpret the value in your code.
   *
   * @schema SnsTopicSpecForProviderTags#value
   */
  readonly value?: string;

}

